server:
  port: 9020
  servlet.context-path: /workspace

spring:
  datasource:
    url: jdbc:postgresql://localhost:9988/lovable-workspace-db
    username: distributedUser
    password: distributedPassword
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioAdmin
  secret-key: minioAdmin123
  project-bucket: projects
